import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { promises as fs } from 'fs'
import Link from 'next/link'
import path from 'path'

export async function getStaticProps() {
  //const postsDirectory = path.join(process.cwd(), 'posts')
  const postsDirectory = "posts/"
  const filenames = await fs.readdir(postsDirectory)

  const posts = filenames.map(async (fileName) => {
    const filePath = path.join(postsDirectory, fileName)
    const fileContents = await fs.readFile(filePath, 'utf8')

    // Generally you would parse/transform the contents
    // For example you can transform markdown to HTML here
    return {
      // Set the current element of posts to a post with post.name and post.content
      id: fileName.replace(/\.md$/, ''), 
      title: fileName.replace(/\.md$/, ''),
      date: "2020",
    }
  }) // End posts Map
  // By returning { props: { posts } }, the Blog component
  // will receive `posts` as a prop at build time
  return {
    props: {
      posts: await Promise.all(posts),
    },
  }
}

export default function Home({posts}) {
  return (
    <div>
      <Head>
        <title>Blog Example</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>
          Blog Example
        </h1>

        <p>
          Welcome to my Blog!
        </p>

        <section>
        <h2>Blog</h2>
        <ul>
          {posts.map(({ id, date, title }) => (
            <li>
              <Link href={`/posts/${id}`}>
                <a>{title}</a>
              </Link>
              <br />
              <small>
                <Date dateString={date} />
              </small>
            </li>
          ))}
        </ul>
      </section>
      </main>

      <footer>
      </footer>
    </div>
  )
}
